# Configuration for the Trading Bot

# Data source settings
# Select the data source to use. Options: 'polygon', 'twelvedata'
data_source:
  active: "twelvedata"

# Trading settings
trading:
  # Using a stock ticker appropriate for Twelve Data.
  symbol: "AAPL"

# Polygon.io specific settings
polygon:
  stream_url: "wss://socket.polygon.io/crypto"

# Twelve Data specific settings
twelvedata:
  stream_url: "wss://ws.twelvedata.com/v1/quotes/price"

# ----------------- Brokerage Settings -----------------
# This section defines the brokerage to be used for executing trades.

brokerage:
  # Select the active brokerage. Options: 'alpaca'
  active: "alpaca"

# Alpaca specific settings
alpaca:
  # The API endpoint for paper trading.
  base_url: "https://paper-api.alpaca.markets"
